package br.com.urbanassist.util;

public enum ClassificationAlgorithm {

	J48, KNN, LINEAR_DISCRIMINANT_ANALYSIS, LINEAR_REGRESSION, LOGISTIC_REGRESSION, NAIVE_BAYES, RANDOM_FOREST, RANDOM_TREE, SUPPORT_VECTOR_MACHINES
}
